name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK/IPA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6 # Specify your desired Flutter version

      

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      # - name: Build IPA
      #   run: flutter build ios 

      - name: Upload APK and IPA
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            # build/ios/iphoneos/Runner.app
      

    
